int menu(Text *);
void show_anagrams(Text);
void uppercase_sort(Text *);
void vowels_to_next_two(Text *);
void swap(Text *);
Text text_input();
void print_text(Text);
void text_free(Text *);
void text_cleaner(Text *);
void wait();
int is_anagram(Sentence, Sentence);
void clear_wstr(wchar_t *);
size_t count_uppers(wchar_t *);
wchar_t get_next_char(wchar_t);
int is_vowel(wchar_t);
int is_sep_word(wchar_t *str, wchar_t *p, wchar_t *word);
int swap_in_string(wchar_t *str, wchar_t *prev, wchar_t *new);
int wuppercase_cmp(const void *, const void *);
int wlexgraphic_cmp(const void *, const void *);
